name: notion_sdk
description: A wrapper for Notion's SDK made for the LiteN app.
version: 0.1.2
homepage: https://liten.app

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

dependencies:
  enum_to_string: ^2.0.1
  http: ^0.13.3
